### ISSUE TITLE
Changes in oil and oil products consumption should be assigned to ISIC 19 (coke and refined petroleum products), not ISIC35T39. Change in coal production and consumption should be assigned to ISIC 05T06, not ISIC 35T59.

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#107]
Currently, changes in oil production/consumption are allocated broadly to the natural gas and petroleum suppliers category, which in turn is allocated to ISIC 35T39. However, ISIC 19 is the correct ISIC code for refined petroleum products suppliers, so to the extent feasible, these costs should allocated to ISIC 19, not ISIC 35T39 (FWIW the jobs per unit output for ISIC 19 is 2X that of ISIC 35T39).

Similarly (but more easily addressed), coal production and consumption is assigned to ISIC 35T39, but ISIC 05T06 is the correct category to assign these changes to.

This is especially important at the state level, because nearly 100% of utility output is domestic but only a very small fraction of petroleum output (<3%) is domestic, so we currently dramatically overstate job losses from vehicle electrification impacts on reduced gas consumption

**Comment by jrissman** [comment]
I assume you're referring to calculated variable `Industry Contribution to Change in Global Output by ISIC Code before Passthrough Costs`.

The revenue changes are not currently assigned entirely to ISIC 35T39, but shared among the energy industry ISIC codes, including ISIC 35T39, proportionately to their output.  I agree we can do this more accurately for 3.0.1.  I'll work on that now.

**Comment by robbieorvis** [comment]
Yep

Sent from my iPhone

On Oct 29, 2020, at 6:40 PM, Jeff Rissman <notifications@github.com> wrote:

﻿

I assume you're referring to calculated variable Industry Contribution to Change in Global Output by ISIC Code before Passthrough Costs.

The revenue changes are not currently assigned entirely to ISIC 35T39, but shared among the energy industry ISIC codes, including ISIC 35T39, proportionately to their output. I agree we can do this more accurately for 3.0.1. I'll work on that now.

**Comment by jrissman** [comment]
Here's how I'm breaking it down by fuel:

- coal goes to ISIC 05T06
- crude oil goes to ISIC 05T06 (because ISIC 19 is for refined products, and 05T06 is for raw extracted product)
- refined petroleum products (i.e. all petroleum types except crude oil) go to ISIC 19
- natural gas goes to ISIC 35T39
- electricity goes to ISIC 35T39
- biomass and biofuels go to ISIC 01T03
- other energy suppliers - this is mostly hydrogen, district heat, and uranium - go to ISIC 35T39

**Comment by robbieorvis** [comment]
This looks good. If you wanted be exactly precise, uranium should probably go to mined energy products.

Sent from my iPhone

On Oct 29, 2020, at 7:06 PM, Jeff Rissman <notifications@github.com> wrote:

﻿

Here's how I'm breaking it down by fuel:

  *   coal goes to ISIC 05T06
  *   crude oil goes to ISIC 05T06 (because ISIC 19 is for refined products, and 05T06 is for raw extracted product)
  *   refined petroleum products (i.e. all petroleum types except crude oil) go to ISIC 19
  *   natural gas goes to ISIC 35T39
  *   electricity goes to ISIC 35T39
  *   biomass and biofuels go to ISIC 01T03
  *   other energy suppliers - this is mostly hydrogen, district heat, and uranium - go to ISIC 35T39

**Comment by jrissman** [comment]
Completed in commit 1cec763.  (I did assign uranium cash flow changes to ISIC 05T06, as you suggested.)

I've discovered that the changes in cash flows attributable to particular fuels within the NGPS industry can have different signs (for example, a reduction in refined petroleum product revenue and an increase in crude oil revenue).  This is a dynamic we were failing to capture before, when we formerly took the total revenue change for the NGPS industry and assigned it to the corresponding ISIC codes proportionally to their output (so the NGPS's industry's contribution to the change in revenue had the same sign for all ISIC codes).  Now, those changes may have different signs, so the effects on particular ISIC codes may be larger than you would expect.  This means that this fix turned out to be more important for accuracy than I realized, and I am glad we did it.
