### ISSUE TITLE
New policy lever for policy mandated retirement of power plants (as opposed to additional retirements policy lever)

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#110]
We should add a new policy lever that reads in a separate power plant retirement schedule, like the structure for BPMCCS and PMCCS in the power sector.

The current issue is that we are unable to model earlier retirements of a single power plant, because using the current policy lever would just increase the total retirements, not shift in time when the retirement is happening.

An alternative mechanism like the one here would allow users to specify a separate retirement schedule to evaluate the impact of an earlier than scheduled retirement for the same set of power plants.

**Comment by jrissman** [comment]
I could add this new policy lever today for inclusion in EPS 3.1 without affecting the Texas EPS results.  But because it's a new policy, it would require you to update the FoPITY files and WebAppData "PolicyLevers" tab for all regional models that will be launching on the 3.1 platform, even if they are not using the new policy.  Do you want me to go ahead and add this policy lever to U.S. 3.1 today (and you will make the necessary updates to all the state/regional models to use the latest 3.1 executable before they launch), or would you prefer we hold this feature until the next release after 3.1?

**Comment by robbieorvis** [comment]
I think let’s hold off for now, given how tight time is before we launch five models (US, India, Virginia, Minnesota, Texas).

But would love to see it in 3.2 at some point ☺

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
Sounds wise.  It's better not to try to rush something in before all those model launches.  This will be no problem to include in a subsequent release.

**Comment by jrissman** [comment]
Completed in a79a7d1 and f957aa6.  It currently has no data in the non-BAU schedule for the U.S. national model and this lever is set not to show in the web app, because my understanding is that this policy is for the benefit of some state-level models, not the U.S. national model.  But if you do want to use it for the U.S. national model, you can go ahead and enable the levers in WebAppData and add non-BAU retirements data to elec/CRbQ.
