### ISSUE TITLE
Modify COVID impact to account for changes in total GDP, not just GDP growth rates

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#111]
We had a call with another modeling group today in which they explained their approach to modeling COVID. They similarly adjust GDP growth rates but use this to find a modified total GDP number. The modified total GDP or GDP per year is then used to estimate the short and long term impact of COVID on energy consumption.

This seems like a better approach than we have now, because once the annual growth rate change goes back to zero, we assume the economy is right back where it was pre-COVID. In reality, there is likely to be a sustained longer term impact, which would be captured by an effect to total GDP instead of just a change to GDP growth rates.

**Comment by jrissman** [comment]
There seem to be two misunderstandings in this request. You don't need any change from me.

First, the only reason it returns to the previous trajectory is because that is what is specified in FoPITY input data.  Our model works based on change in GDP relative to BAU, not based on GDP growth rates.  The lever is set in terms of growth rates because that is the most understandable way people think about GDP.  Sonia was a strong proponent of formatting the lever units this way, and I agreed with her.  Accordingly, I'm not going to change this.  

Second, the fact that the gdp returns to BAU trajectory has nothing to do with use of growth rate units to set the lever.  Growth rate is just a year over year change for the depth of covid impact in year 1 of the pandemic.  
The reason it returns to BAU trajectory is because of the assumption that the impact of covid declines by the same percentage in each future year, which causes it to asymptote at zero.  We do this because of the lack of projections of covid economic impacts beyond 2 years out.  You are effectively saying you want it to asymptote at some value other than zero.  I'm not sure if that's really how the impact of covid will look decades from now, but if you have a citable data source for the impacts of covid more than 2 years ahead that shows a permanent GDP reduction, you can simply choose a different asymptote in line with that new data source.  Without a data source, I see no reason to opt for a permanent reduction versus a temporary one.  But if you do change this, it's an edit to data in FoPITY and doesn't involve me.

Finally, I will mention that once covid impacts are included in BAU data, likely in the next AEO, we need to set this control lever to zero.  It was always a stand-in for use only during the period when the actual input data hadn't been updated to reflect the pandemic.  So your choice right now will only exist for the next release or two, after which point, we will probably update to an input dataset that includes covid impacts and will cease using this lever entirely.

I'm removing myself from this issue and tagging it "Data Only".

**Comment by robbieorvis** [comment]
Got it, thanks. Reassigning to @mkmahajan

**Comment by jrissman** [comment]
Sure thing! :-)

I would not be surprised if there are better projections about the longer-term impacts of COVID now than there were at the start of the pandemic.

**Comment by mkmahajan** [comment]
Updated to use CBO's 2020 Economic Outlook (comparing their January report to their July update, which has GDP projections through 2030). We now recover to BAU GDP growth rates by 2030 but never recover in terms of real GDP. Comparing the BAU trajectory to a scenario with no COVID impacts, there is a ~1% difference in emissions after 2030.

**Comment by robbieorvis** [comment]
This is awesome, and closely aligned to other groups.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]
