### ISSUE TITLE
Bug in calculation of hard coded costs for technologies with non-zero soft cost data

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#123]
When calculating _Construction Cost per Unit Capacity before Construction Subsidies_ for onshore wind, solar PV, and offshore wind, the model does not add back in soft costs when the capital costs are hard coded in future years, circumventing the endogenous learning. This results in too low of costs and prohibits use of the soft cost policy lever.

For example, this: 

IF THEN ELSE(
  CCaMC BAU Construction Cost per Unit Capacity[onshore wind es] > 0,

  CCaMC BAU Construction Cost per Unit Capacity[onshore wind es]
  * (1 - RnD Electricity Capital Cost Perc Reduction This Year[onshore wind es]),

  (
    First Year Hard Costs per Unit Capacity[onshore wind es]
    * This Year Solar and Wind Hard Costs as Fraction of First Year Hard Costs[onshore wind es]

    + Soft Costs per Unit Capacity[onshore wind es]
  )
  * (1 - RnD Electricity Capital Cost Perc Reduction This Year[onshore wind es])
)

Should instead be: 

IF THEN ELSE(
  CCaMC BAU Construction Cost per Unit Capacity[onshore wind es] > 0,

  CCaMC BAU Construction Cost per Unit Capacity[onshore wind es]
  * (1 - RnD Electricity Capital Cost Perc Reduction This Year[onshore wind es])
  +**Soft Costs per Unit Capacity[onshore wind es]**,

  (
    First Year Hard Costs per Unit Capacity[onshore wind es]
    * This Year Solar and Wind Hard Costs as Fraction of First Year Hard Costs[onshore wind es]

    + Soft Costs per Unit Capacity[onshore wind es]
  )
  * (1 - RnD Electricity Capital Cost Perc Reduction This Year[onshore wind es])
)

Texas is asking for some more data updates, so we have time slip this update in if you can get to it ASAP.

**Comment by jrissman** [comment]
Well, the existing approach was intentional, and I don't think it produces costs that are too low, assuming the user supplied the input data expected by the model.  The user is asked to enter the total capital costs (not just hard costs) in CCAMC-BCCpUC.  To add soft costs to this number in Vensim, in `Construction Cost per Unit Capacity before Construction Subsidies`, would be double-counting the soft costs.  Notice that in the code you quote above, in the "else" part of the "if" statement, the soft costs are being added to `First Year Hard Costs per Unit Capacity[onshore wind es]`, not to `CCaMC BAU Construction Cost per Unit Capacity[onshore wind es]`.  This is why the cost total is correct in the current implementation, whether or not the model is using endogenous learning.

However, it is true that the policy lever that reduces soft costs does nothing in models that hard-coded their power plant prices in future years, i.e. bypassing the endogenous learning system.  The soft costs were initially designed as a way to realistically constrain the cost reductions you get from endogenous learning, and they seemed unnecessary to model differently from other costs if endogenous learning is not being used.  But there is no reason we _couldn't_ allow this policy to work to reduce soft costs even when endogenous learning is not being used.  We might as well enable it.

Also, the soft costs are not currently reducing the share of the total cost that is affected by the R&D policy lever in the case where the model is not using endogenous learning.  That seems like another thing we could improve.

I can work on this today.

**Comment by jrissman** [comment]
Completed in 35798fd.

Note that this will only affect the output if the policy scenario is using either (1) the capital cost R&D lever applied to solar PV, onshore wind, or offshore wind, or (2) the soft cost reduction policy lever.  Therefore, you won't see any change in the output for the BAU case, nor for any policy case that doesn't use either of those levers.

All of this only affects models that disabled endogenous learning for power plant capital costs.

The Texas EPS does use hard-coded power plant costs, but the only policy scenario currently in the Texas EPS does not use either of the soft cost reduction lever nor the R&D lever for power plant capital costs, so I don't think this change will affect EPS Texas (though you may now wish to begin using one or both of these levers in the Texas policy scenario, since the levers will now work for EPS Texas).
