### ISSUE TITLE
Convert O&M costs in CCaMC to time series variables

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#124]
NREL's ATB shows fixed O&M costs falling by up to 60% by 2050, depending on the power plant type.

**Comment by jrissman** [comment]
I could do this one without affecting the frozen Texas EPS results (because you could use the same costs in all years for Texas EPS).  Do you want me to go ahead and do this now?  You will need to update all state models to use the new EPS.mdl EPS.vpmx and time-series CCaMC files if I implement this now, but it should not change their results unless you choose to move to time-varying data, so the update should only take you a very short time per state EPS.

**Comment by mkmahajan** [comment]
Sure, that would be great. Thanks so much, Jeff.

**Comment by jrissman** [comment]
Completed in e0a4eac.
