### ISSUE TITLE
New F-gas data

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#136]
[HFC_Data.xlsx](https://github.com/Energy-Innovation/eps-us/files/5796122/HFC_Data.xlsx)

We received new and vastly improved HFC data, which is attached.

Let's integrate this for the next model update.

It only covers HFCs, so we'll need to add in SF6 and PFCs. Those are comparatively small and can likely just be held constant or use some of the existing methodology in BPEiC. PERAC will also need to be updated to ensure we hit the Kigali values in this file.

**Comment by jrissman** [comment]
Since you don't have any new data source for PERAC, you can use the sophisticated multiplier system we built into BPEiC and PERAC specifically to handle the situation where a partner wanted to replace EPA BPEiC data for a chemical or sector.  Find ratios between the EPA data and the data you have (after adjusting your new data to include PFCs and SF6), then enter the ratios as multipliers.  Copy those multipliers to PERAC, to keep it in sync with BPEiC.

If I remember correctly, I believe the current PERAC values already have the potential to bring F-gas emissions to zero when all four F-gas policies are used, and zero emissions of course complies with Kigali.  These levers should still be able to reach zero if adjusted using the multiplier system.  (PERAC plays no role in the BAU case.)

**Comment by mkmahajan** [comment]
Done in commit 8c1b66
