### ISSUE TITLE
Disaggregate health impacts by demographic factor

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#154]
EPA's COBRA tool has detailed county-by-county estimates of health impacts from changes in emissions by sector/technology covering the full range of our mortality and morbidity indicators. We could run a batch of modeling runs in COBRA testing emissions reductions in different sectors and pollutants to develop county level estimates to changes in health outcomes, then combine these with demographic data from the Census to estimate how different populations (by race, income, etc...) would be impacted by our policies. 

EPA's COBRA tool is here: https://www.epa.gov/cobra

This would significantly enhance our ability to answer questions on equity, though we would still be making the assumption that emissions are proportionately reduced.

This source also includes health impacts from ammonia, so if we wanted to add ammonia to the model we would have the health data.

**Comment by jrissman** [comment]
The downloadable version of COBRA grinds to a halt when trying to do this, but the EPA's new COBRA web interface is able to configure and complete the runs in a timely manner and export all results as an Excel file.

**Comment by jrissman** [comment]
Completed in commits d558fd9, 0b8204b, c5bb581, and 6c5d9d5.

I followed the methodology suggested by Robbie, using COBRA to produce premature mortality impacts disaggregated by pollutant and by U.S. county, then mapped the demographics of every county onto the premature mortality numbers, then obtained national averages.

I excluded "age bracket" from the set of demographic traits for which we make predictions because the biology of how air pollution affects people differs greatly by age.

The biology of how air pollution affects people does not change that greatly with sex, race, or Hispanic/Latino status, so we have the confidence needed to allocate deaths according to population shares on a per-county basis.  However, those demographic groups do have different underlying (BAU) death rates, and air pollution effects on death are typically calculated as a change in BAU death rate.  We're not capturing that here.  But using COBRA to obtain static multipliers already excludes certain effects (like population growth), which is a more important confounding factor.  Recall that issue #113 involves moving to a full-blown population tracking structure using death rates and the like, which is necessary for maximum accuracy.  At the time when we implement issue #113, we can implement differential BAU death rates by sex, by race, and by Hispanic/Latino status, if such data are available.  (Getting future projections of these things might be a bit challenging, because they depend on economic progress of people in disadvantaged groups over the next 30 years, since BAU death rates are tied to things like access to quality health care or living in low-pollution neighborhoods, which are in turn tied to income.)  In the meanwhile, the way #154 (this issue) has been implemented is consistent with the way the EPS is currently estimating health impacts and should be as accurate as is possible using the EPA's COBRA tool plus Census data under the current framework.
