### ISSUE TITLE
Add new policy lever(s) restricting fossil fuel exports

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#156]
We should explore adding new levers that would restrict fossil fuel exports. These could be used in deep decarbonization scenarios to prevent fuel that we might otherwise assume would be exported from being exported. This would likely be more relevant with the updated industry data we now have and would notably have a potentially large impact on jobs outputs.

**Comment by jrissman** [comment]
This lever has existed in the EPS since 2.0.0.

Not long ago, we had an email discussion about the pros and cons of using a non-zero setting for this lever as part of the reference scenarios, and you decided not to use it in the reference scenarios.  You can revisit that decision anytime with neither any structural nor input data updates to the EPS, so I'm closing this issue.

**Comment by robbieorvis** [comment]
Ugh duh thank you. I looked at the cross-sector policy list but this in industry. Sorry for the duplication.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D73694.57ED53F0]
________________________________

Check out our book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]
