### ISSUE TITLE
Retrofitting policy needs to account for reductions in energy consumption from other policies

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#159]
I noticed today looking at the buildings sector graph in the NDC scenario that there is something weird going on: the building emissions drop and plateau at zero, but it's not a smooth curve. This is happening due to the way the retrofitting policy is implemented, which ignores other policy driven reductions in energy consumption, for example from efficiency and electrification. I believe this issue is easily addressable. Right now the retrofitting calculations estimate a BTU shift based on the start year components energy consumption (to avoid dealing with new buildings, I believe). The calculations could either move to using a percentage, which would be the percent reductions from retrofitting * remaining building stock share * remaining share of building stock that can be retrofit, then adjust the components energy use by the percentage OR we could revise the calculations for BTU reduction from retrofitting to use the calculated components energy use value instead of start year values (I believe the first approach is easier).

**Comment by jrissman** [comment]
Normally when retrofitting curve is not smooth, it simply means you finished retrofitting all the pre-existing buildings before the model's end year, so the policy stops having an effect abruptly at some point.  If you don't like the lack of smoothness, the usual thing to do is simply to choose a weaker retrofitting policy setting, so it doesn't finish retrofitting existing buildings until 2050.  Either that, or you can accept that the curve isn't smooth, because a curve that isn't smooth doesn't always indicate a problem in the modeling.

Yes, the retrofitting policy only applies to preexisting buildings.  It used to apply to all buildings, but we changed it to only apply to preexisting buildings because it made no sense applying it to buildings (or components) added during the model run, and also, the calculations for applying it to stuff built during the model run were very convoluted.

The feeling at the time we redesigned it was that this policy represents fixing things like leaky ductwork and old crumbling building envelopes and such, and that these fixes would not be affected much by new policy or how efficient most new components are, since the improvement potential would be mostly based on how damaged/old the existing building stock is.  The policy is not meant to be used for lighting, appliances, or discrete components like that.  We could change the assumption and factor in some effect from policies, but the current design isn't just some sort of mistake: it was an intentional choice we made at the time, thinking this is how to best represent fixing up old buildings.  I'm not yet convinced it was the wrong choice.

(`bldgs/BRESaC` is set up to apply the reductions directly to heating and cooling and ventilation, rather than envelope, because the effect of this policy is brought into the calculation flow after we've already applied envelope effects.  In this case, it doesn't matter that we apply it directly to heating and cooling rather than to envelope (i.e. this doesn't introduce error).)

**Comment by robbieorvis** [comment]
The settings in the NDC lever are weaker than retrofitting the entire stock (they are set to .15), so it is not related to that. The issue is that it estimates BTU reductions based on start year components energy use, but many pieces of equipment have been improved with other policies, lowering energy reductions. I already tested moving this to a percentage reduction based on the factors I mentioned in the issue: multiplying the remaining stock by the retrofit policy lever settings and then by the percent reduction in energy consumption from the retrofitting policy, and this eliminated the problem. Please take a look at the suggested approach (when you are back on EPS modeling days) and let me know if you see anything wrong with it, but I think it will work.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D7400E.4A381C30]
________________________________

Check out our book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
Okay, will do!  Sounds good.

Would you mind pushing your edited version of EPS.mdl to a side branch (maybe named "#159") so I can look at it on my next EPS workday?

**Comment by robbieorvis** [comment]
Sure thing!

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D74034.4E3D3470]
________________________________

Check out our book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
I've reviewed the work done in branch #159.  The general approach to energy use looks sound to me!  However, there are some errors introduced into the cash flow calculations, because you are changing a variable from BTU to a percentage, and the cash flow calculations use operations that assume the variable contains a BTU quantity.  (The units need to be updated too.  It currently fails a unit check, which could have been a flag that something isn't right.)  I will use the general calculation approach you created, but I will fix the units, update the variable names to better reflect what they will contain, and update the cash flow calculations to work correctly with the percentage changes.

**Comment by jrissman** [comment]
Completed in 15d3df0
