### ISSUE TITLE
Add costs for transit fares (bus, rail, airfare), vehicle insurance, parking, and vehicle annual licensing/registration/property taxes

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#161]
Currently, the EPS does not assign any costs to the consumers of public transit (passenger HDV, passenger rail) or air travel, only to the equipment owners. However, to correctly capture changes in household spending from policies, we need to add in these costs.

The BTS has data on revenue from fares for public transit, ridership, and average fares, which can be used together to estimate the total spending per passenger mile and then allocated to each type of travel mode. See these three sources: 

https://www.bts.gov/content/average-passenger-fares-current-dollars
https://www.transit.dot.gov/ntd/data-product/2019-data-tables
https://www.bts.gov/content/average-passenger-revenue-passenger-mile

**Comment by robbieorvis** [comment]
Full email thread for background: 

Hi Robbie,

The trips themselves are tracked in passenger HDV and passenger rail modes.  The vehicle and fuel costs are charged to the vehicle owners (private companies and government).  However, bus, rail, ship, and air fares paid by riders are not currently tracked.

The ownership shares of each vehicle type are already in the model, so we know how we would allocate fare revenues.  We would just need to calculate the fare amounts.  This would involve coming up with a multiplier to convert passenger-miles by each of these four modes (bus, passenger rail, passenger ferry, and passenger aircraft) to fare in dollars.

The U.S. model treats passenger ships as recreational boats (which have no fare), but other countries treat that subscript as passenger ferries.  So other countries would need a multiplier covering passenger ships.

We do have a policy that reduces air travel, so we also need a multiplier for aircraft, even though we are shifting away from aircraft rather than to aircraft.  Consumers save the cost of airfare, which could be large savings.

If you can provide the necessary multipliers in an Excel file, I can do the cash flow programming in Vensim.

Can you open a ticket for this on GitHub eps-us repo?

Jeff




On May 20, 2021 11:13 AM, Robbie Orvis <robbie@energyinnovation.org> wrote:
Hey Jeff,
 
Quick question for you: are the costs of “consuming” transportation options covered in the model for things that require fares and tickets? For example, if we shift a lot of people out of cars and into buses, are we accounting for the fares riders have to pay to ride the bus? Same thing for air and rail travel. I’m asking because if we look at policy scenarios with heavy mode shifting, I want to be sure the costs of alternative passenger mode options are being covered appropriately so that we don’t overstate changes in household spending.

**Comment by jrissman** [comment]
Completed in aa488e4.

Note that this changes mode shifting from a negative-cost policy to a positive-cost policy on the cost curves.  I think this is an improvement because it always was odd that mode shifting to transit was the most cost-saving policy in the cost curve often.  But it seems pretty expensive now.  I feel pretty confident with the data I added for cost per passenger-mile because it comes straight from BTS National Transportation Statistics, but you might want to review it anyway, in variable `trans/FpUCD`.  In particular, one thing you could change is the extrapolation method.  I estimated fares (after inflation) would continue to increase at the historical rate they have in the past, but you could instead hold inflation-adjusted fares constant if you think that produces more realistic future cost projections.

The other thing you could consider is increasing the share of trips that are eliminated (rather than shifted to bus or rail) in `trans/RTMF` because in the post-pandemic world, it's become more obvious that people can work from home and meet remotely, so the pre-pandemic estimates of the potential to completely eliminate trips feel like potentially an under-estimate to me now.

I'm going to leave this one open because I think other EPS team members should review the extrapolation method in `FpUCD` and the mode shift recipients in `RTMF`.  You can test by using a policy package that contains only the "passenger LDV mode shifting" policy set to the maximum of 26%, and then view the Cost Curve to get the cost per ton abated.  Assigning @mkmahajan and @robbieorvis for data review.

**Comment by jrissman** [comment]
It seems worthwhile to put in the insurance, vehicle registration, and parking costs for passenger LDVs.

I can try to code it in a way that lets you put these things in for any vehicle type, but if you don't have data on (say) the insurance costs paid by public transit agencies to insure their buses, I think that's probably okay.  As you note, public transit agencies receive a lot of their funding from things other than fares, and we're not trying to model their internal financials - we're only trying to get the right cost impacts from mode shifting.  Insofar as transit agencies are funded by fares (say, 30%, or whatever), the insurance must already be priced into the fares to a similar degree.  So this is mainly of issue for passenger LDVs, where the owner is paying the insurance, registration, and parking fees, and isn't just passing them through to customers or getting them covered by government funding.

I'll try to add these other costs soon so we can do a public 3.3.1 release soon.

**Comment by robbieorvis** [comment]
Agreed – great!

________________________________
Robbie Orvis
Senior Director of Energy Policy Design
+1 415-799-2171
1225 Eye Street, N.W.
Suite 904
Washington, D.C. 20005
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***

**Comment by jrissman** [comment]
I've added insurance costs and parking costs to the model.  I've also updated the aircraft to recipient mode shifting distribution to favor more virtual meetings and less use of passenger rail, given the poor state of passenger rail in the U.S.  (For Europe, China, and Japan, you might want to adjust this back to favor passenger rail a bit more.)

I've also updated the projection of changes in future fares to assume they follow inflation (i.e. they increase about as fast as other goods' prices increase).  This past 12 months, transportation services have actually increased in cost more slowly than inflation (see BLS data [here](https://www.bls.gov/news.release/cpi.nr0.htm), with a 3.9% increase in transportation services compared to a 6.8% increase for all items).  Therefore, our previous projection that transportation services would increase in cost faster than inflation in the future seems likely to be wrong.  Overall inflation is an average, so half the economy has to increase in cost more slowly than the overall inflation rate, mathematically speaking.

All of these changes help to fix the problem with the mode shifting policy looking too expensive.  It now is more reasonable, though still probably slightly too expensive.

I haven't added the vehicle registration/license fees yet because I disbelieve the AAA source Robbie linked to.  I'm going to look for a better source.

**Comment by jrissman** [comment]
Okay, I've been looking into the topic of taxation of cars more deeply.  I think the AAA value struck me as high because some states have an annual property tax on cars, while and other states do not have vehicle property taxes.  In some states (such as California), the taxable value of a vehicle declines as the car depreciates, but other states do things differently.  [This article](https://www.mansionglobal.com/articles/which-u-s-states-charge-property-taxes-for-cars-220298) says that in Connecticut, the tax is levied on 70% of the vehicle's retail value and is a tax rate of 2.6%, and doesn't appear to decline with depreciation.  They say this works out to an annual tax of $650/car in Connecticut, which is about right, given the average new car sales price in the U.S. in early 2020 (before pandemic-related inflation) was $37,876 (per [Kelley Blue Book](https://www.prnewswire.com/news-releases/average-new-vehicle-prices-up-nearly-3-year-over-year-in-february-2020-according-to-kelley-blue-book-301015050.html)).

[This article](https://www.mansionglobal.com/articles/which-u-s-states-charge-property-taxes-for-cars-220298) says that 23 states don't charge annual vehicle property taxes, and of the ones that do, the average per vehicle ranges from $25 in Louisiana to $1,011 in Virginia.

So the AAA number of $753 looks more reasonable in this light, particularly considering it is not just property tax, but also includes the vehicle registration / licensing fees, which exist in all 50 states.

I think I've satisfied myself that the AAA value (1) is probably a reasonable average for the U.S., and (2) doesn't include sales taxes from the initial purchase of the car, which makes it a suitable value to use in this part of the model.

**Comment by jrissman** [comment]
Okay, this set of features is finally done and appears to be working well.  Adding the costs of fares, insurance, parking, and licensing/registration/property tax helps to capture on-road transportation-related cash flows in much better detail.  It also greatly improves the accuracy of the cost-effectiveness calculation for the mode shifting policy (i.e. in the Cost Curve diagram).  Closing this issue.
