### ISSUE TITLE
Mismatch between BFPIaE and calculated primary energy consumption

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#164]
In the TX model, I've noticed that the sum of fuel production and imports minus fuel exports from fuels/BFPIaE can be quite far off compared to calculated energy consumption in the model. This is likely a result of different downscaling methodologies in different files, and can partially be resolved with input data edits. But I suspect this issue is cropping up in other regions. For example, natural gas production in the US BFPIaE is scaled based on the AEO, but we know the EPS projects less electricity generation from natural gas and more from wind/solar than the AEO. In 2020, (production+imports-exports) for natural gas from BFPIaE is 105% of the calculated Total Primary Energy Use. But by 2050, that drops to 83%.

Because there can be a mismatch between the values in BFPIaE and calculated energy consumption, the variable Percent Change in Domestic Fuel Production by Fuel may be incorrect, leading to incorrect results for industrial fuel consumption and emissions impacts. 

I don't have a concrete suggestion right now given the complexity of the fuels production/imports/exports calculations, but I'd be happy to hop on a phone call to discuss this.

**Comment by mkmahajan** [comment]
Please ignore my comment about the reason for the discrepancy in the US - I had it backwards assuming that we'd be off for that reason! But in fact, (production+imports-exports) as extrapolated by AEO results _in less_ natural gas consumption than the calculated Total Primary Energy Use variable in 2050.

**Comment by jrissman** [comment]
Thanks for flagging this.

Given that we're currently taking in input data for fuel consumption (in the various sectors), as well as for production, imports, and exports (in `BFPIaE`), the only way to guarantee they are aligned is to stop taking input data for one of these values and instead calculate it in Vensim from the other three.

(Even if we use input data from a single, high-quality source for all four values, such as the EIA AEO, the EPS builds its own BAU electricity and transportation sectors, so a BAU EPS result for electricity or transportation fuel use won't equal the BAU value from the EIA AEO.  So it isn't just an issue of needing better alignment between different input data tables.)

So which one of the four is best to calculate in Vensim?  Given that we require highly granular input data for consumption (in the sectors), this definitely must be one of the three that we take in as input data.  So we would have to get rid of the input data for either BAU production, BAU imports, or BAU exports, and calculate it instead.  Among these options, probably calculating BAU production makes the most sense, since it is more closely linked to the policies and structure of the modeled region than imports or exports.

I put in the calculation and compared the calculated production values to the ones from `BFPIaE`.  Unsurprisingly, we see the largest differences in the case of the more minor fuels, such as uranium, biomass, lignite, and MSW.  We also tend to see higher differences for transportation fuels, since the transport sector is one where the EPS builds its base case.  See the following spreadsheet for the comparison.

[2021-06-29 Fuel Production Input vs. Calculated Values.xlsx](https://github.com/Energy-Innovation/eps-us/files/6737925/2021-06-29.Fuel.Production.Input.vs.Calculated.Values.xlsx)

I suppose it's probably worth moving to the calculated values, but maybe we can double-check some of the data in the sectors and in BFPIaE to see why the differences are so large and if anything should be done to close the gap, particularly for fuels that cannot be easily explained by the EPS building BAU transport and electricity sectors.  "LPG, Propane, and Butane" is one where there should not be a large difference, for instance.

**Comment by jrissman** [comment]
Actually, we use a number of non-AEO sources in `BFPIaE`, and it looks like it's those sources that are giving the largest mismatch with the calculated production values.

I think I'm going to go ahead and swap in the calculated values.  I hope you can take a few minutes to test the model carefully after this change, just to make sure it doesn't cause any strange behavior, particularly for the less-important fuel types.

**Comment by jrissman** [comment]
Done in 85f06c4.  But I'd like to leave this issue open until you have a chance to test it and make sure it looks reasonable and fixes the issue you've encountered.  One thing that you might consider looking at is to compare the values of `Percent Change in Domestic Fuel Production by Fuel` for a typical policy package before and after commit 85f06c4, to make sure it didn't change anything in a way that looks unreasonable.  (If you feel satisfied with it, you can close the issue.)

**Comment by robbieorvis** [comment]
Jeff, thanks for looking into this.

I’m not sure though that using production as the calculated variable makes a lot of sense. It would seem to reason that in most countries (again thinking beyond the US here), each country would try to reduce imports to the greatest extent possible. This also is somewhat visible in US data, where production for example of crude oil has been growing consistently for the most part but imports of crude oil vary year-to-year. It’s obviously trickier than this: demand, consumption, and production all depend on global oil prices and economic drivers such as extraction costs, but I actually think we should be using imports as the calculated variable under the assumption that most economic production is already being pursued (or will in line with BAU production estimates) and that imports are likely what’s to change in a BAU. The other rationale for this is that domestic production for any given country is constrained by resource availability and local economic considerations, whereas imported energy can basically be thought about as infinite (at least for things like oil) bank to draw from.

Before testing, what do you think about this?

________________________________
Robbie Orvis
Senior Director of Energy Policy Design
+1 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA 94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***D76D94.709EED50]

**Comment by jrissman** [comment]
Well, not all fuels are traded internationally to a significant degree.  Imports are constrained by import/export capacity, whereas production is unconstrained.  For a fuel type not traded much, imports and exports are unimportant, so if you want consumption and production to balance, production has to be the calculated quantity.

For other fuels, like crude for the U.S., I agree that imports should be the calculated quantity used to balance production, exports, imports, and consumption.  But for KSA, crude imports will always be zero, and exports should be the calculated quantity.

So I guess this varies based on fuel type and geography, so it needs to be data-driven.  I'll add a new input data variable that allows you to set which of the three variables is the calculated one, customizable for each EPS deployment.

**Comment by robbieorvis** [comment]
Good thoughts and solution!

Sent from my iPhone

On Jun 30, 2021, at 12:19 PM, Jeff Rissman ***@***.***> wrote:

﻿

Well, not all fuels are traded internationally to a significant degree. Imports are constrained by import/export capacity, whereas production is unconstrained. For a fuel type not traded much, imports and exports are unimportant, so if you want consumption and production to balance, production has to be the calculated quantity.

For other fuels, like crude for the U.S., I agree that imports should be the calculated quantity used to balance production, exports, imports, and consumption. But for KSA, crude imports will always be zero, and exports should be the calculated quantity.

So I guess this varies based on fuel type and geography, so it needs to be data-driven. I'll add a new input data variable that allows you to set which of the three variables is the calculated one, customizable for each EPS deployment.

**Comment by robbieorvis** [comment]
I might suggest a tiered system in cases where consumption drops below the first choice

Sent from my iPhone

On Jun 30, 2021, at 12:26 PM, Robbie Orvis ***@***.***> wrote:

﻿ Good thoughts and solution!

Sent from my iPhone

On Jun 30, 2021, at 12:19 PM, Jeff Rissman ***@***.***> wrote:

﻿

Well, not all fuels are traded internationally to a significant degree. Imports are constrained by import/export capacity, whereas production is unconstrained. For a fuel type not traded much, imports and exports are unimportant, so if you want consumption and production to balance, production has to be the calculated quantity.

For other fuels, like crude for the U.S., I agree that imports should be the calculated quantity used to balance production, exports, imports, and consumption. But for KSA, crude imports will always be zero, and exports should be the calculated quantity.

So I guess this varies based on fuel type and geography, so it needs to be data-driven. I'll add a new input data variable that allows you to set which of the three variables is the calculated one, customizable for each EPS deployment.

**Comment by jrissman** [comment]
Sorry, I don't understand the tiered system proposal.  Can you explain in more detail?

**Comment by robbieorvis** [comment]
Like with the guaranteed dispatch mechanism: value of 1 would mean a category is reduced first, then things with a 2, then things with a 3

Sent from my iPhone

On Jun 30, 2021, at 12:33 PM, Jeff Rissman ***@***.***> wrote:

﻿

Sorry, I don't understand the tiered system proposal. Can you explain in more detail?

**Comment by jrissman** [comment]
Oh, I see, to avoid negative values.  Only relevant for reductions, not for increases.

**Comment by jrissman** [comment]
Completed in 26b7912.
