### ISSUE TITLE
Make share of battery price a time series variable

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#179]
The idea here is to set up endogenous learning for EVs similar to learning for wind/solar, where the share of soft costs are a time series variable. This change will help us more closely match other estimates from ICCT, NAP, and UBS, which show that there are significant cost declines in the non-battery vehicle components as well. 

We'd like to get this into 3.3 if possible. I can work on this on a separate branch today, then pass off to @jrissman for review.

**Comment by jrissman** [comment]
This sounds good and the edit should be pretty straightforward.  Please go ahead and make the edit.  Note that we'll want to remove the words "Start Year" from the variable name `SYBSoEVP Start Year Battery Share of Electric Vehicle Price`, which involves updating the file acronymn-key.xlsx.  And since this might be the last update to EPS.mdl and EPS.vspmx before a public release, please do the tasks starting with number 2 under the "Tasks in Vensim" section of the developer wiki (at https://github.com/Energy-Innovation/eps-us/wiki/Tasks-to-release-a-new-version-of-an-existing-model ).  The checklist contains just simple stuff I do every time I commit an update to EPS.mdl / EPS.vpmx, like making sure the Output Total CO2e is the selected workbench variable and the currently-displayed sheet is the first sheet.

**Comment by jrissman** [comment]
Actually, we want to replace the words "Start Year" with the word "BAU" in the variable name, because the share will be different in policy scenarios.

**Comment by mkmahajan** [comment]
Merged into develop in commit 060ae89. Note that I also subscripted this variable by Vehicle Type so that we have the flexibility to customize further in the future. 

I also followed the Tasks in Vensim steps above.

**Comment by mkmahajan** [comment]
I revisited this calibration for freight LDVs today and further subscripted this variable by Cargo Type in order align with other sources.
