### ISSUE TITLE
Customize ccs/BFoCPAbS to have separate tabs for industrial energy and process emissions

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#203]
Our CCS policy levers allow us to set separate policy values for industrial energy and process emissions, but the file ccs/BFoCPAbS that sets the BAU Fraction of CCS Potential Achieved only allows for a single value for industry. 

We just revisited the data in BFoCPAbS based on a recent Rhodium study that projects BAU CCS capacity through 2035 and found that the potential is significantly higher than what we had before. For that reason, making the distinction between industrial energy and process emissions could be important. In all, Rhodium finds 142 MMT of capture capacity by 2035: https://rhg.com/research/carbon-capture-american-jobs-plan/. @jrissman it would also be good to hear what your reaction is to that number for a BAU case.

**Comment by jrissman** [comment]
Subscripting `ccs/BFoCPAbS` for Industry by `Emissions Type` should be quick/easy.  I'll do it.

It looks like our current BAU value for CO2 sequestered by Industry in 2035 is 127 MMT (in variable `This Year Pollutants Sequestered by Industry Sector`).  127 MMT is within the error range of 142 MMT, so I would say we're not that different from Rhodium in total quantity.  (I saw you updated these figures today in the U.S. EPS - I haven't checked what they were back in the 3.3.0 release.)

In terms of judging whether Rhodium's projections (from their Figure 3) are realistic, I like the approach you took in BFoCPAbS comparing the Global CCS Institute's database of plants in operation, under construction, and in planning stages against Rhodium's figures.  The sum of average capacity figures through 2025 (the latest data in the CCS Institute database) is 84 MMT, which makes 142 MMT by 2035 feel reasonable.  Though we might want to exclude power sector projects, since Rhodium's figure is for the industry sector.  That gives a value of 50 MMT through 2025.  Today's value is 18 MMT, so that is a fast growth rate if they all come online.  It seems possible to hit 142 by 2035 even in just the Industry sector, though that's a bit more of a stretch for a BAU case.

I haven't personally looked into the effect of the CCS tax credit on likely future CCS deployment in the U.S.  I know this is going to be a part of the BBB Act too, if that passes, though that shouldn't be part of BAU until it passes.

That said, I am surprised by Rhodium's distribution of how this capacity breaks down by industry.  Here's their figure 3:

![Figure-3-1](https://user-images.githubusercontent.com/7120106/141006032-47781707-a241-4f46-8e63-f1449c0fa63f.png)

Natural gas processing, in yellow, is just 7% of the 2035 CCS capacity in Rhodium's projection.  But today, natural gas processing is 70% of all U.S. CCS capacity.  (Rhodium's projection of 10 MMT actually implies a shrinkage of CCS from natural gas processing relative to today, and growth in many other industries.)  Maybe they are assuming natural gas will be a much smaller industry by 2035 than it is today, and so CCS opportunities will decline accordingly.  But I think a rapid phase-out of natural gas is not realistic for BAU case.

So the distribution in Rhodium feels surprising to me.

One other thing I noticed is that it looks like you're assigning ethanol production to "chemicals 20" in `BFoCPAbS` but I thought we considered ethanol plants to be part of the refining sector.  It's worth checking BIFUbC to see where we assigned ethanol plants' energy use.

**Comment by jrissman** [comment]
Also note that the EPS's current figure for 2020 is 11 MMT sequestered, which is below the capacity of plants in operation according to the Global CCS Institute database (18 MMT).  It's true that even non-suspended plants don't operate at 100% capacity factor.  I estimated a global value of 87% capacity factor as part of my industry work, which if it applies to the U.S. would imply a U.S. sequestration quantity of 15.6 MMT in 2020, still somewhat above the 11 MMT value we have in there right now.

**Comment by jrissman** [comment]
I've made the structural change, so all remaining work on this issue is data-only.

**Comment by mkmahajan** [comment]
Thanks, @jrissman!

I'm glad you reminded me about ethanol falling in the refining industry. I have made that data adjustment. I also like your point about the 87% capacity factor. Since Rhodium reports capture capacity rather than actual CO2 capture, I think it would be nice to apply that capacity factor to the calculations in BFoCPAbS. **Would you be able to share your calculations for that so I could include it in the file?**

I agree that Rhodium's number for natural gas processing in particular in odd. Rather than assuming a decline in capacity, I used the CCS Institute's data on planned plants through 2027, then extrapolated the trend through 2035. That results in 21.5 MMT capture capacity for natural gas processing in 2035, up from 17 MMT in 2027. For all other industries, I relied on Rhodium.

Even though we have more CCS for natural gas processing than Rhodium, note that I excluded Rhodium's 23 MMT for hydrogen, as that is it's own sector in the EPS. Issue #195 would add CCS for hydrogen production, in which case we could add that in.

**Comment by jrissman** [comment]
That sounds like a great approach for addressing natural gas processing.

I've sent you the spreadsheet with the 87% CCS capacity factor calculation, and some explanation, by email.

**Comment by mkmahajan** [comment]
CCS capacity factor calculation incorporated in commit 3d48016

**Comment by jrissman** [comment]
@mkmahajan FYI, in `BFoCPAbS BAU Fraction of CCS Potential Achieved by Sector` on the tab "Rhodium" the ethanol refining is still assigned to the "Chemicals" industry and not the "Refining" industry in the latest commit.  Is that intentional?

**Comment by mkmahajan** [comment]
Thank you @jrissman! Fixed in commit b418d1d
