### ISSUE TITLE
Add new graphs to webtool requested by multiple partners

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#214]
We've had some overlapping requests for new graphs from a few partners from different regions. These should be pretty straightforward to calculate in Vensim and to include in the WebApp:

- Share of electricity generation from clean sources (%)
- carbon intensity of electricity generation (tCO2e/MWh)
- electricity intensity (kWH/GDP)
- CO2-only, broken down by energy vs process (stacked area graph)
- CO2 process emissions, broken down by industry (stacked area graph)
- CO2 industrial energy emissions, broken down by industry (stacked area graph)

The latter three are particularly relevant for China, where there is a strong emphasis on CO2-only indicators. Given that we have big plans for new China national and provincial models, I think it would be great to add these all.

**Comment by jrissman** [comment]
These look good.  Note that this is in addition to the graph changes in issue #212, which should be done at the same time.

We currently don't have the X-per-unit-GDP graphs set to display in the web interface for the U.S. model.  That stems from when we added these graphs in the EPS 2.x series because India needed GDP intensity graphs.  In the 2.x series, we didn't calculate the policy-driven change in GDP, so we didn't want to show the GDP intensity graphs for any other region (because all the metrics were being divided by the BAU GDP).  Now in the 3.x series, the EPS does calculate the GDP impacts of the policy package, so our main rationale for hiding the graphs no longer applies.  Do you want me to start showing the X-per-unit-GDP graphs in the U.S. web interface?

**Comment by robbieorvis** [comment]
Thanks, Jeff. Don’t think we need to show it for the US, because it’s not typically a point of interest. But it does sound like for other regions it is.

________________________________
Robbie Orvis
Senior Director of Energy Policy Design
+1 415-799-2171
1225 Eye Street, N.W.
Suite 904
Washington, D.C. 20005
www.energyinnovation.org<http://www.energyinnovation.org/>
Sign up here to receive EPS modeling updates<https://energyinnovation.org/energy-policy-solutions-updates/>
***@***.***

**Comment by mkmahajan** [comment]
Completed
