### ISSUE TITLE
Apply industry carbon tax to industrial energy use only

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#227]
The EPS currently calculated the industry carbon tax revenue based on the variable Industrial Fuel Use, which includes both fuels used for energy and nonenergy purposes:
![image](https://user-images.githubusercontent.com/56732097/167667130-b4f428c3-6bcf-4a5c-b9c7-af994e966056.png)

I asked Chris about this, and his response was:
"Every carbon pricing policy I've ever seen is based on CO2 from fuel combustion. So, chemical feedstocks would not add to an emitters' compliance obligations in a typical setup. (There are some exceptions around offsets, which are typically projects in uncovered sectors, which may cover methane from rice cultivation or methane from coal mining.)"

This suggests we should instead calculate industry carbon tax revenue based on the variable Industrial Fuel Use for Energy Purposes rather than Industrial Fuel Use. 

This seems like a high priority item to get right. @jrissman and @robbieorvis would you be okay with me making this edit for 3.4 rather than waiting for 3.5?

**Comment by robbieorvis** [comment]
Yes, I think so, but defer to Jeff.

From: mkmahajan ***@***.***>
Sent: Tuesday, May 10, 2022 11:40 AM
To: Energy-Innovation/eps-us ***@***.***>
Cc: Robbie Orvis ***@***.***>; Mention ***@***.***>
Subject: [Energy-Innovation/eps-us] Apply industry carbon tax to industrial energy use only (Issue #227)


The EPS currently calculated the industry carbon tax revenue based on the variable Industrial Fuel Use, which includes both fuels used for energy and nonenergy purposes:
[image]<https://user-images.githubusercontent.com/56732097/167667130-b4f428c3-6bcf-4a5c-b9c7-af994e966056.png>

I asked Chris about this, and his response was:
"Every carbon pricing policy I've ever seen is based on CO2 from fuel combustion. So, chemical feedstocks would not add to an emitters' compliance obligations in a typical setup. (There are some exceptions around offsets, which are typically projects in uncovered sectors, which may cover methane from rice cultivation or methane from coal mining.)"

This suggests we should instead calculate industry carbon tax revenue based on the variable Industrial Fuel Use for Energy Purposes rather than Industrial Fuel Use.

This seems like a high priority item to get right. @jrissman<https://github.com/jrissman> and @robbieorvis<https://github.com/robbieorvis> would you be okay with me making this edit for 3.4 rather than waiting for 3.5?

**Comment by jrissman** [comment]
Okay, go ahead.  Please remember to make the corresponding change to the BAU version of that variable too, which is just to the right on that sheet.  Thanks for the fix.

**Comment by mkmahajan** [comment]
I made this fix to both Industry Sector Carbon Tax Revenue and BAU Industry Sector Carbon Tax Revenue.

I also checked where we calculate the carbon tax expenditures by industry, and that was already correctly applied to only fuel used for energy purposes. I also checked the debugging assistance page, and I do not see any issues there after this edit.
