### ISSUE TITLE
Extend power sector capital cost smoothing capabilities

### ISSUE THREAD

**Issue by jrissman** [Energy-Innovation/eps-us#239]
In order to better represent payments-over-time for power plants and other capital equipment in the power sector:

- Change `Smoothing Time for Generation Construction Cost` into an input data variable subscripted by `Electricity Source`.
- Add a smoothing time to the costs to construct transmission lines
- Add a smoothing time to the costs to construct grid batteries

All these smoothing times could come from the same Excel file (something like `ESCCST Electricity Sector Capital Cost Smoothing Times`) with three blue tabs, one for power plants (subscripted by plant type), one for transmission lines, and one for batteries.

This one is very straightforward, so I think @mkmahajan you can go ahead and do it without me, and let me know if you run into any trouble.

**Comment by mkmahajan** [comment]
Based on our email thread RE: Replacing SMOOTHI with DEPRECIATE STRAIGHTLINE, I have implemented the following steps suggested by Jeff:

1.	Replace SMOOTHI with DEPRECIATE STRAIGHTLINE in the equation for Change in Electricity Sector Construction Costs.
2.	Change the smoothing time used to an input data variable with GET DIRECT CONSTANTS rather than a hard-coded value in Vensim.  I’d call it “Smoothing Time for Electricity Sector Capital Expenditures”. 
3.	Add DEPRECIATE STRAIGHTLINE to Change in Transmission Construction Costs and to Change in Electricity Sector Battery Costs, mimicking the way DEPRECIATE STRAIGHTLINE is implemented for Change in Electricity Sector Construction Costs.  Use the same smoothing time input variable from the last step.
4.	Add a new variable that is a version of Electricity Sector Change in Amount Spent on Capital Equipment by ISIC Code that has DEPRECIATE STRAIGHTLINE applied to it.  Use a new input data variable, “Smoothing Time for Electricity Price Changes”.  Set it to a semi-generous value, such as 10 years.
5.	Use the new smoothed capital cost variable you just created to replace Electricity Sector Change in Amount Spent on Capital Equipment by ISIC Code in the equation to calculate Change in Electricity Supplier Expenditures After Subsidies per Unit Electricity Produced.
6.	Then, set Smoothing Time for Electricity Sector Capital Expenditures as short as we find tolerable.  A smoothing time of 1 would eliminate smoothing and therefore have the clearest view of construction job impacts, but it would exhibit the most jagged behavior on graphs.  If the resulting discontinuities and jagged behavior are too much or cause problems elsewhere in the model, you could try a smoothing time of 3.  If it’s still too jagged, you could keep the current smoothing time of 5, which we know works.  There is no reason to test longer smoothing times than 5, which would worsen the issue of spreading out construction jobs over time.

I'll leave this issue open until we have time to discuss together.

**Comment by mkmahajan** [comment]
I've updated the smoothing time for electricity price changes to 20 and am leaving the smoothing time for capital expenditures at 3.
