### ISSUE TITLE
Add Direct Air Capture

### ISSUE THREAD

**Issue by ssonniaa** [Energy-Innovation/eps-us#27]
This would obviously require speculative assumptions about costs and energy use, but it would be interesting to include something along these lines, mostly so we can show people that this is not the cure-all they hope it would be.

**Comment by jrissman** [comment]
I implemented direct air capture (DAC) in commit 9231a20.  The outer bound potential for the DAC lever is based on an extremely aggressive 1.5-degree scenario in a major, recent study focusing on DAC.  Even in this aggressive scenario, DAC only starts to be phased in commercially after 2045, so we only see it in the last few years of the model run (which ends in 2050).  If we someday extend the EPS model run end date to 2100, DAC could be much more important.

Energy use, associated emissions, electricity demand, costs, and full cost allocation (e.g. the division of payments between domestic and foreign equipment suppliers, and labor) are all handled.

The DAC characteristics are all data-driven, so the potential DAC capacity, energy intensity, and cost progression of DAC can be modified in input data without further structural changes from me.  Note that DAC cost and energy efficiency improvements are currently taken in from input data, because there isn't enough time in the model run (2046-2050) for endogenous learning curves to perform well (and they work best when we're not starting from zero, since they are extremely sensitive to the size of the installed base in the start year, and some years of real-world commercial deployment data can help to calibrate the curve).  I don't anticipate going to an endogenous learning curve for DAC unless the model run is extended to 2100, and we _might_ stick with exogenous learning even in that case.

In Vensim, all of this is implemented as part of a new "geoengineering" sector.  It would have been very difficult to add DAC to the industry sector, which has very detailed financial accounting flows into which DAC (and other geoengineering measures) would not have fit.  The geoengineering sector will keep the data more organized and also facilitate the addition of other geoengineering measures in the future, should we decide to add more.

Geoengineering measures tend to come in two varieties: those that remove carbon from the atmosphere, and "direct thermal management" measures that aim to cool the Earth without removing carbon from the atmosphere (like sulfate injection or orbital mirrors).  Since the EPS is an emissions-based model, not a global temperature model, CO2-removal technologies are the most obvious fit.  That said, it can still be meaningful to put a direct thermal management geoengineering measure into the EPS, because the EPS can estimate the energy demands and costs of building, deploying, and operating those measures.  Geoengineering must happen at such a massive scale that these impacts can be large compared to other sectors of the economy, which illustrates the serious difficulty of relying on geoengineering as a climate solution.

In the Web interface, DAC is categorized under the "Research and Development" policy category, because it is not a good idea to create a new "Geoengineering" top-level policy category just for a single policy lever, and R&D is the main activity we'd be doing for the next couple decades if we want to further DAC.
