### ISSUE TITLE
Update methodology for TDM to use a change in thing*miles traveled rather than percentages

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#34]
The current methodology actually leads to increased emissions in India, because the miles traveled by transport mode looks much different than other countries (low passenger LDV and high passenger HDV).

**Comment by jrissman** [comment]
Before doing this issue, we should consider whether we prefer to implement #1 instead (break TDM into several component policy levers), as TDM component policy levers would likely each have their own units.

**Comment by jrissman** [comment]
Completed in commit f4154da (which also addressed issue #1).  Note that I've renamed this policy "Mode Shifting" instead of "TDM" to avoid jargon and improve user-friendliness.  (The policy description text still explains in detail what it is.)  It should now be easy to represent any country or region.  You may wish to update the values in `trans/RTMF` if you don't like my choices about what people do when they shift away from a particular mode - this is part of the policy design, so I don't think we need to cite a source for `RTMF`.  I set the max lever bounds for the U.S. based on IEA Blue Shifts, so setting the levers to their current max settings should be similar to setting the old TDM policy to 100%.  But now the policy is more customizable, and you should have an easier time representing India, or any other country or region.  The subscripting of the lever itself allows you finer control (essentially breaking what used to be a single TDM policy package into vehicle-specific measures, with the ability to further refine what these represent by adjusting `RTMF`).
