### ISSUE TITLE
Allow CCS from industrial process emissions

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#47]
Industrial CCS is currently capped by the variable Industrial Sector Pollutant Emissions from Fuels for Energy Purposes before CCS. Where the potential for CCS from process emissions exists (e.g. cement, natural gas processing, ethanol), we should consider updating the cap.

I believe we've discussed this in the past but I don't see it in the issue tracker - is there an issue that would prevent this?

**Comment by jrissman** [comment]
It should be doable.  Thank you for adding it to the issue tracker.

It's not actually a data-only change because the equation in the variable "This Year Pollutants Sequestered by Industry Sector" (and its BAU equivalent) need to be updated.  We'd also have to scan through and just make sure everything is working after making the simple updates - there might be other assumptions in the code somewhere that need to be altered.  But it doesn't strike me as a big job.

**Comment by jrissman** [comment]
This is done.  Also, note that this provides an ability to eliminate CO2 process emissions (aside from cement clinker substitution, which has long existed), so this also helps with issue #33.  Closing this issue.
