### ISSUE TITLE
Create template for WebAppData

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#49]
We had discussed the idea at one point of making a more generic template for aspects of WebAppData that would autopopulate in the correct places. For example, we had discussed a template for output graphs where users would enter updates to variable and subscript names and an indicator of whether to include or exclude certain elements in the output graphs. We started talking about a similar template for the policy levers tab.

Such a template, even if just for the output graphs, would make updating WebAppData to new regions considerably easier and less error prone, particularly when undertaken by a partner.

**Comment by jrissman** [comment]
e61a968 adds the UnitControlCenter (for controlling output graph units), and I extended it to also cover the two Policy Lever units that typically involve unit conversions (Carbon Tax and Electricity Generation Subsidy).  It also adds the "Include?" column for Output Graphs.  Todd is going to handle the implementation of skipping undesired graphs in his import scripts, so we don't need to do more than add that column to WebAppData.

Since there had been other changes to WebAppData since the version in the "data" branch, I created a combined version of WebAppData manually that incorporates all the latest changes.  I merged the data and develop branches, so both will have the up-to-date WebAppData.

This is as far as we wish to go in terms of templatizing WebAppData, so I'm closing this issue.
