### ISSUE TITLE
Allow for BAU decreasing soft costs for power plant technologies

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#78]
Currently, the model separates soft costs and hard costs and only hard costs decline based on cumulative installed capacity, with soft costs remaining constant. Soft costs can only be affected by policy. In practice, however, large improvements in cost are being achieved through improvements in soft costs in the BAU case (NREL ATB has good documentation on this). As such, we need a way to represent the BAU improvement in soft costs without additional policy.

A times series variable, BAU Improvement in Soft Costs Relative to Start Year, should take care of this.

We are likely to overstate the costs of renewables without this tweak.

**Comment by jrissman** [comment]
We normally avoid introducing a second "improvement rate" variable for anything defined as a time-invariant variable.  We just change the time-invariant variable to a time-series variable.  Then if you want to use a fixed improvement rate, you can do that in Excel, or you can use any other sort of improvement pattern you like, so it is more flexible than using a separate "improvement rate" variable.  It also avoids cluttering up the model structure with extra variable names and arrows.  Is there a reason you must have a separate "improvement rate" variable and can't put the improvements into a time series in Excel?

I can convert endo-learn/SYSoCCtaSC and endo-learn/SYSoCCtaSC to be in units of dollars per MW, rather than a percentage, if that would be more convenient.

**Comment by robbieorvis** [comment]
Hi Jeff,

I think that's probably fine, but I'll just flag that one of the challenges here is that we have endogenous learning, so setting a time series percentage is a bit tricky because it means the soft costs will change based on the endogenous learning rate, unless the time series is a multiplier on the start year costs (in which case this would work just fine and it's what I'd propose).

**Comment by jrissman** [comment]
I'll convert endo-learn/SYSoCCtaSC and endo-learn/SYSoCCtaSC to be in units of dollars per MW, so you won't have to make a time series of a percentage of a changing underling value.  The dollars per MW will be start year soft costs, which you then reduce according to whatever rate or schedule you prefer, so it will be simple.

**Comment by robbieorvis** [comment]
Okay, great. Thank you. This will help close the loop on some power sector issues we were having with new data.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
Structure is completed in 001ec05.  Rather than retain the variable `endo-learn/SYSoCCtaSC`, it made more sense structurally to add soft costs as an additional table to existing time-series cost variables: `elec/CCaMC` for utility-scale onshore wind, offshore wind, and solar PV, and `bldgs/CpUDSC` for distributed solar PV.

I've got temporary soft cost data in `elec/CCaMC` and `bldgs/CpUDSC` right now, based on the fractions we were formerly using in `endo-learn/SYSoCCtaSC` (converted to $/MW).  That probably is pretty reasonable, but I think the whole point of building this feature was because Robbie wanted to enter his own set of time-series soft costs.  Therefore, I assume you'll want to replace my temporary data in `elec/CCaMC` and `bldgs/CpUDSC` prior to 3.0 launch, so I'm not going to close this issue now.

Tagging @robbieorvis and @mkmahajan, handing it off to you!

**Comment by jrissman** [comment]
After the electricity sector update in commit 4013c4f, have you either updated the soft cost time series values, or decided to keep the values I had in there?  (E.g. can we close this issue?)

**Comment by robbieorvis** [comment]
Megan updated these, so we can close it

Sent from my iPhone

On Aug 7, 2020, at 12:34 PM, Jeff Rissman <notifications@github.com> wrote:

﻿

After the electricity sector update in commit 4013c4f<https://github.com/Energy-Innovation/eps-us/commit/4013c4fce51060f9a4dd3c37a41d03144bbdf108>, have you either updated the soft cost time series values, or decided to keep the values I had in there? (E.g. can we close this issue?)

**Comment by jrissman** [comment]
Great!
