### ISSUE TITLE
Prevent fuel switching in power sector when not cost-effective (easy fix)

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#88]
Right now, the power sector will fuel switch as the relative price between two fuels and their plant dispatch costs change. However, this fails to also capture how the market prices are changing. The problem here is that under the current methodology, the model will fuel switch even if doing so creates more capacity of a power plant type that is immediately uneconomic and would be subject to early retirement. We should use the sum of incremental fuel price differences and also market prices changes in calculating how much capacity is fuel shifted.

We can achieve this by including the _Change in Relative Cost vs BAU_ in the equation for _Perc Shifts in Power Plant Fuel Use_. The model then calculated the sum of the _Change in Relative Dispatch Cost for Each Plant Type_ PLUS the negative of _Change in Relative Cost by Source vs BAU_, and only shift when that sum is >0. 

This prevents the model the from shifting to a fuel type that is immediately uneconomic.

**Comment by jrissman** [comment]
Doesn't the current approach only switch to a plant type that is cheaper than the current type?  Meaning, sure, the type it switches to might be uneconomic, but only if its current type is _even more uneconomic_ than the type it's switching to, right?  (There must be some reason the existing plant hasn't retired yet, despite being uneconomic.  Most likely, it's because there is so much existing capacity of that plant type that there hasn't yet been time for it all to retire since it became uneconomic.)

In the case of retrofits, it may make sense not to switch from an uneconomic plant type to a less-uneconomic-but-still-uneconomic plant type, because it might not be worth spending the money to do, say, a coal-to-gas retrofit unless you were expecting positive return on investment for the retrofit project.

On the other hand, in the case of switching between one petroleum fuel to another, it's a costless fuel switch.  The plant should probably switch to whichever fuel type is least uneconomic, even if that type is still uneconomic.  So it strikes me that the current behavior might be valid for fuel switching (but not retrofitting).

**Comment by jrissman** [comment]
Note that the same model structure handles both costless fuel shifting and retrofit-involved fuel shifting.  The only difference is whether any cost is specified in `elec/FSCaFoCC` (and you'd use a different elasticity in `elec/EoPPFTSwFP` for a costless fuel shift versus a retrofit-involved fuel shift).

![Capture](https://user-images.githubusercontent.com/7120106/90686316-03466f80-e220-11ea-81d4-07722afe78a8.PNG)

**Comment by jrissman** [comment]
So if need be, we can check for non-zero costs in `FSCaFoCC` and handle this one way if it's a costless fuel shift, and a different way if it's a retrofit-involved fuel shift.  I just want to make sure we wouldn't be preventing power plant operators from reducing their losses by switching to a less-uneconomic fuel type, because it's not uncommon for businesses losing money to do things to slow the rate of money loss, even if those things aren't enough to actually make a profit.  (Maybe some might even do a minor retrofit to slow losses, but I think we are probably safe in disregarding that, as it might be hard to secure financing for a retrofit to a plant type that the financier thinks will never make money.)

**Comment by robbieorvis** [comment]
The issue I’m seeing relates to natural gas and coal with a high carbon price. Natural gas becomes much less uneconomic than coal, but still very uneconomic and prone to early retirements. It does not make sense for the model to shift coal to gas plants (retrofitting) when they are immediately uneconomic.

What you are discussing is fuel shifting (non-retrofitting) that is in theory induced by changes to fuel prices (e.g. fuel price deregulation in KSA). In that case, as you mention, the fuel is a drop in replacement, and it makes sense that a plant might shift to something less uneconomic if still required to run and if there are no additional costs to switch. This is the key I think, which is what you are alluding to.

There is no distinction between these two pathways in the model at the moment, which is perhaps an issue, but I’m more concerned about the coal to gas switching at the moment than the fuel switching, e.g. for KSA, since they may never even get to this model platform.

To correctly address this, we probably need to factor in the costs of retrofitting, which could be handled in the subsequent financing calculation updates we have been discussing for 3.1 down the road.

Then, you might have to break this apart into retrofitting and fuel switching. Plants that are capable of costless fuel switching would do so as soon as it becomes economic based on cost differentials just between the dispatch costs of the power plants, and not based on the market price.

For retrofitting, plants would take this on if the sum of the cost differential and the market impact was greater than or equal something like the investment costs to do so + a rate of return (like a weighted average cost of capital, which we are thinking of introducing as part of the financing calculations).

(This is also approaching how you could model CCS, by the way, if we ever wanted to consider that).

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by robbieorvis** [comment]
This is a smart way to handle this for now. If costless, then don’t look at changing market conditions. If there is a cost, then add those in.

In the long run, we’ll probably need to refine this, but this would work for now as a hotfix.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment]
Okay, I'll add the check against market conditions as you suggested, only in cases where there is a non-zero capital cost to switch fuels (i.e. retrofit-involved fuel switching).  This way, the 3.0.0 structure will remain suitable for regions that have multiple, drop-in fuel options (such as KSA, or likely anywhere that seriously uses oil-burning power plants) while also fixing the issue you found with U.S. coal-to-gas retrofits.

**Comment by jrissman** [comment]
Done in dd093b5.

Note that instead of subtracting `Change in Relative Cost by Source vs BAU` from `Change in Relative Dispatch Cost per Unit Electricity Output of Each Pair of Plant Types`, I just check the early retirement code to see if the target plant type is subject to early retirement, since we already have a check for this in that code, and I'd rather re-use the same check then write new code to check it in a slightly different way here.  That way, if we decide to update the way we determine which plant types are economic, it will automatically affect both the early retirement and the fuel shift retrofit calculations, instead of requiring us to remember to do it in two places.  I made a new calculated, Boolean variable `Is Plant Type Subject to Economic Early Retirement` to consolidate the results of this check into a single, clearly named variable, which we use in both places where we check whether a plant type is economic.

(And in any case, whether or not the target plant type is economic doesn't depend on what the source plant type was, so it's probably better not to involve `Change in Relative Dispatch Cost per Unit Electricity Output of Each Pair of Plant Types` in this check anyway.)

The results I'm getting when testing dd093b5 show that a high carbon tax no longer causes coal plants to shift to NG plants.
