### ISSUE TITLE
Update Policy Lever: "Additional Battery Storage Annual Growth Percentage" to MW units

### ISSUE THREAD

**Issue by oashmoore** [Energy-Innovation/eps-us#93]
For state level EPS development with RMI, it would be useful to have the "Additional Battery Storage" policy lever units be in MWs rather than percentages. 

Many states have very low battery storage deployment in a BAU scenario. The current policy lever uses a 0-100% annual growth rate scale. With a percentage scale, it is hard to represent the speed and scale of growth needed. Additionally, many state targets are in MWs. It would be easier to have this scale show MW growth by 2050, rather than adjusting compounding percentages to match state-level MW targets.

**Comment by jrissman** [comment]
Completed in commit 6b41ccd.  We now use a fraction of potential as the slider unit, with the potential set in MW in an input data file.  This is the same way as we handle similar policies like the one for Demand Response.  This is more user-friendly than setting the lever in MW directly, and also, it is easier to adapt to different countries, because the slider bounds don't have to be changed for every deployment - changing the input data is enough.  The guidance text has been updated to specify the MW in the BAU case and the potential, so users setting the lever can easily convert between MW and share of potential.
