### ISSUE TITLE
Edit variable Capacity Retired Early so that it reports 0 when all capacity of a given plant type has been retired

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#94]
I found a minor bug today when looking at the jobs for the early coal retirement policy. When testing the policy at the max slider bound of 10,000 MW per year and the default implementation schedule, all coal is retired by 2033. However, the variable Retiring Generation Capacity continues to be ~10,000 MW in each year through 2050. That means we continue to see decommissioning costs through 2050, even though all coal capacity has already been retired. I think we need a fix for the variable Capacity Retired Early so that it accounts for this rather than taking values straight from the policy setting in each year.

**Comment by jrissman** [comment]
Fixed in 0b08b25.  Note that I didn't change the formula in `Retiring Generation Capacity` because it is used elsewhere to check when to lock out the construction of plant types that retire to zero.  We already have a different version of this variable, `Retiring Generation Capacity by Quality Level` that is correctly limited.  So the only change was to switch which variable is checked in the decommissioning cost calculation.
