### ISSUE TITLE
The variable Total Energy Related Emissions doesn't remove geoengineering emissions 

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#95]
This bug came up because of some overly aggressive direct air capture potential data from the TX team (I've directed them to Jeff's write-up on this issue to support using the default data we supplied). But their values highlighted the fact that the variable Total Energy Related Emissions doesn't remove geoengineering emissions, which can lead to incorrect results on the CO2e Emissions by Sector graph.

**Comment by jrissman** [comment]
This was a design decision, rather than a bug, but we can revisit it and consider whether to change how this behaves.

You are right that "energy-related emissions" normally means only emissions from fossil fuel combustion.  But for CCS (ordinary CCS, not direct air capture; DAC), we only include the **_net_** energy-related emissions.  That is, if some energy-related emissions are captured by CCS, we only count the energy-related emissions that reach the atmosphere, not the energy-related emissions that were stored underground and never touched the atmosphere.  We felt that this was aligned with the definition of "emissions" - i.e. it isn't actually "emitted" if it doesn't make it to the atmosphere.

Having already built CCS that way, we had to decide if we wanted to treat DAC consistently or differently.  We chose to make it consistent with CCS, so that geoengineering would contribute negative energy-related emissions.  (Geoengineering also has positive emissions from the fuel burned to power the DAC process, but these positive emissions are smaller than the amount of captured CO2.)

If this is not aligned with what people want or expect to see on the energy-related emissions graphs, we could change it so that the captured CO2 from DAC is excluded, and only the emissions from energy burned to power the DAC process are included on the energy-related emissions graphs.  Is this desirable from a the perspective of producing outputs model users expect and desire, even though it treats CO2 captured by CCS and CO2 captured by DAC differently from each other?

**Comment by jrissman** [comment]
I guess I am leaning toward making this change, since fitting with the plain meaning of the words "energy-related" seems more important in this case than to treat all captured CO2 similarly.

**Comment by mkmahajan** [comment]
Thanks for clarifying. It makes sense that this was a decision around consistency. I support making the change because of the term "energy-related," especially because the CO2e Emissions by Source Type graph plots geoengineering as a separate wedge. Therefore, we see the geoengineering emissions reductions plotted as both the separate geoengineering wedge and as part of the energy wedge.

**Comment by jrissman** [comment]
Done in 527f643.
