### ISSUE TITLE
Hydrogen fuel blending

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#98]
For a future model update, consider how we might allow for hydrogen fuel blending with natural gas. This request came from Bruce Nilles, who notes that studies show up to 30% of drop in blending of hydrogen with natural gas in the existing distribution system

**Comment by jrissman** [comment]
The EPS already supports this and no work is needed.  Hydrogen is allowed as a fuel in the Industry, Buildings, and Transportation sectors (as well as in smaller sectors, like district heating and geoengineering).  If you want to represent, say, a 10% blend of hydrogen in the natural gas supply, then use the Buildings fuel shifting policy to shift 10% of buildings fuel from natural gas to hydrogen.  It won't incur extra hydrogen transport infrastructure costs, which implies it's being delivered in existing pipelines.  For industry, we have a fuel shifting policy where we specify the share going to hydrogen and to electricity, recently improved per issue #116, which is a good approach because the share you electrify depends on delivered heat temperature, and in vehicles it's based on the vehicle technology (e.g. you need hydrogen-burning vehicles), so I think we are already representing this correctly in all sectors.

I'm closing this because no work needs to be done.  You might want to inform Bruce Nilles that the EPS supports his use case.
